name       : easyeffects
version    : 7.0.7
release    : 5
source     :
    - https://github.com/wwmm/easyeffects/archive/refs/tags/v7.0.7.tar.gz : 08aa95bd15be16185409dbb0aec13000034fc128ea63c05f62620c0c877acb1c
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Audio effects for PipeWire applications
description: |
    Limiter, compressor, convolver, equalizer and auto volume and many other plugins for PipeWire applications
conflicts  :
    - pulseeffects
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(fftw3f)
    - pkgconfig(fmt)
    - pkgconfig(glib-2.0)
    - pkgconfig(gsl)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libbs2b)
    - pkgconfig(libebur128)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(lilv-0)
    - pkgconfig(lv2)
    - pkgconfig(nlohmann_json)
    - pkgconfig(rnnoise)
    - pkgconfig(rubberband)
    - pkgconfig(samplerate)
    - pkgconfig(sigc++-3.0)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(speexdsp)
    - pkgconfig(tbb)
    - appstream-glib
    - desktop-file-utils
    - itstool
    - zita-convolver-devel
rundeps    :
    - calf
    - lsp-plugins
    - mda-lv2
    - yelp
    - zam-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
